// Category: Bangladesh
// ~10 passages, ~500 words each, English. Fill in via content-writing pass.
import type { ExamPassage } from "./types";

function wc(text: string): number {
  return text.trim().split(/\s+/).length;
}

const ARTICLES: { title: string; text: string }[] = [
  {
    title: "The Ready-Made Garment Industry",
    text: `Bangladesh's ready-made garment industry stands as one of the most remarkable economic stories of the past four decades. What began in the late nineteen seventies as a handful of small factories producing shirts for export has grown into a sector that now accounts for the overwhelming majority of the country's export earnings. Millions of workers, a large share of them women, are employed across thousands of factories scattered throughout Dhaka, Chittagong, and other industrial zones. The industry's rise transformed not just the national economy but also the social fabric of the country, giving many women their first opportunity to earn a steady wage outside the home.

The garment sector's success rests on several factors working together. Bangladesh offers a large and relatively low cost labor force, proximity to major shipping routes, and decades of accumulated expertise in cutting, sewing, and finishing garments for international brands. Buyers from Europe and North America source everything from basic t shirts to more complex outerwear, and the country has steadily moved up the value chain by investing in better machinery and more skilled supervisors. Trade agreements that grant preferential access to certain markets have also played a meaningful role in keeping Bangladeshi products competitive against rivals in other parts of Asia.

Growth of this scale has not come without serious challenges. Factory safety became a matter of urgent national and international concern after a series of tragic building collapses and fires drew global attention to conditions inside some facilities. In response, the industry undertook a large scale program of structural inspections and renovations, supported by international buyers, labor groups, and the government working together. Many factories today operate under far stricter safety and fire codes than a decade ago, though the work of ensuring consistent enforcement across every facility continues.

Looking ahead, the industry faces pressure to modernize further. Automation is slowly changing how garments are cut and assembled, and buyers increasingly expect suppliers to demonstrate responsible environmental practices, from wastewater treatment to energy efficiency. Diversification is another theme shaping the sector's future, as manufacturers experiment with higher value products like technical fabrics and branded fashion lines rather than relying solely on low margin basics. Workers' rights organizations continue to push for higher wages and stronger bargaining power, and periodic wage negotiations remain a closely watched event in the national conversation.

Despite the challenges, the ready-made garment sector remains central to Bangladesh's economic identity. It has lifted millions of families out of poverty, financed a significant share of the country's infrastructure development through foreign exchange earnings, and demonstrated how a developing economy can build a globally competitive industry from limited natural resources. Its continued evolution, balancing growth with worker welfare and environmental responsibility, will likely shape much of the country's economic trajectory in the years to come.`,
  },
  {
    title: "Dhaka's Urban Growth and Challenges",
    text: `Dhaka, the capital of Bangladesh, is among the fastest growing megacities in the world. Over the past several decades, a combination of rural to urban migration, natural population growth, and the concentration of jobs, education, and government services in one place has swollen the city's population many times over. People arrive from villages across the country in search of work, education for their children, or simply a chance at a better life, and the city has had to absorb this growth at a pace that often outstrips its infrastructure.

The results of this rapid expansion are visible everywhere. Traffic congestion is one of the most familiar complaints among residents, with narrow roads originally built for a much smaller population now carrying an enormous volume of buses, rickshaws, private cars, and pedestrians every day. Public transportation has struggled to keep pace, though recent investments in a metro rail system and expanded bus networks represent efforts to ease the pressure. Housing is another persistent challenge, as demand far outpaces the supply of affordable, well built apartments, pushing many newcomers into informal settlements that often lack reliable water, sanitation, or electricity.

Despite these difficulties, Dhaka remains the undisputed economic and cultural heart of the nation. It hosts the headquarters of most major banks, corporations, and government ministries, along with a growing number of universities, hospitals, and cultural institutions. The city's informal economy, from street vendors to small workshops, provides livelihoods for a huge number of residents who might otherwise struggle to find formal employment. This blend of formal and informal economic activity gives the city an energy and resilience that visitors often remark upon.

City planners and policymakers have increasingly turned their attention to making Dhaka more livable and sustainable. Efforts include expanding green spaces, improving drainage systems to reduce flooding during the monsoon season, and encouraging the development of satellite towns around the city to relieve some of the population pressure at the core. Digital governance initiatives are also being explored as a way to make municipal services, from utility payments to building permits, faster and less bureaucratic for ordinary citizens.

The story of Dhaka's growth mirrors the story of Bangladesh itself: rapid, sometimes chaotic, but full of ambition and resilience. As the city continues to expand, the choices made today about transportation, housing, and environmental management will determine whether it can remain a place where opportunity outweighs hardship. For a nation whose fortunes are increasingly tied to its urban centers, getting Dhaka's growth right is not just a local concern but a matter of national importance. International development partners and urban planning experts continue to study Dhaka as a case study in how a rapidly growing city in the developing world can adapt, offering lessons that may prove relevant to other expanding urban centers facing similar pressures across South Asia and beyond.`,
  },
  {
    title: "Rivers and Deltaic Geography",
    text: `Bangladesh occupies one of the largest river deltas on earth, a low lying landscape shaped by the confluence of several major river systems that flow down from the Himalayas before emptying into the Bay of Bengal. This deltaic geography has defined nearly every aspect of the country's history, economy, and culture, from the fertile soil that supports its agriculture to the transportation networks that connect its towns and villages.

The rivers that crisscross the country carry enormous volumes of water and sediment, especially during the monsoon season when rainfall and snowmelt from the mountains swell their banks. This seasonal flooding, while sometimes destructive, also deposits nutrient rich silt across the floodplains, replenishing the soil each year and supporting the intensive rice cultivation that feeds the population. Farmers have adapted their planting cycles over generations to work with, rather than against, this natural rhythm of flood and recession.

Rivers also serve as vital arteries of transportation and commerce. In a country where road infrastructure has historically struggled to keep pace with population growth, boats and ferries remain an essential way for people and goods to move between regions, particularly in the more remote southern and coastal areas. Riverside markets, fishing communities, and boat building traditions have grown up around this water based way of life, giving many parts of the country a distinct cultural character shaped by proximity to water.

The same geography that provides fertility and transportation also brings significant risk. Bangladesh is highly vulnerable to flooding, riverbank erosion, and cyclones sweeping in from the Bay of Bengal, and rising sea levels associated with global climate change pose a long term threat to low lying coastal areas. Entire villages have had to relocate over the years as rivers shift course and erode the land beneath them, a phenomenon that has made land use planning and disaster preparedness central concerns for policymakers.

In response, the country has invested heavily in flood forecasting systems, embankments, and cyclone shelters that have measurably reduced loss of life during major storms compared to past decades. Engineers and scientists continue to study how best to manage the delta sustainably, balancing the needs of agriculture, fisheries, and growing urban populations against the risks posed by a changing climate. International cooperation on managing shared river systems that originate outside the country's borders remains an important, ongoing dimension of this work.

Understanding Bangladesh without understanding its rivers is nearly impossible. They are simultaneously the source of the country's agricultural abundance and one of its greatest environmental challenges, a duality that has shaped the resilience and adaptability so often associated with the nation and its people. For visitors and scholars alike, the country's waterways remain one of the most immediate and memorable ways to understand its geography, its economy, and its enduring relationship with the natural world.`,
  },
  {
    title: "The Freelancing and Outsourcing Economy",
    text: `Over the past decade, Bangladesh has emerged as one of the more active countries in the global freelancing economy, with a growing number of young people earning income by offering digital services to clients located anywhere in the world. Graphic design, web development, digital marketing, writing, and virtual assistance are among the most common services offered, made possible by widespread internet access and a large population of young, tech literate workers eager to build careers outside the traditional office environment.

This shift has been driven by several converging factors. Internet penetration has expanded rapidly across cities and, increasingly, smaller towns, bringing connectivity to people who previously had limited access to global markets. Training centers, both government supported and privately run, have sprung up to teach practical digital skills, often targeting young graduates who face a competitive traditional job market. International freelancing platforms have made it far easier for a worker in a mid sized Bangladeshi city to find a client overseas than it would have been through any conventional channel just a generation ago.

The appeal of freelancing lies partly in its flexibility. Workers can often set their own hours, take on multiple clients, and build a portfolio without needing to relocate to a major city or work for a single employer. For many young people, particularly women who may face social or logistical barriers to conventional office jobs, freelancing offers a practical way to earn income while balancing other responsibilities. This has made the sector an important, if often underappreciated, contributor to household incomes in many parts of the country.

Alongside individual freelancing, a parallel outsourcing industry has grown, in which companies handle larger scale projects such as software development, customer support, and business process work for international clients. These firms often operate more like conventional businesses, employing teams of specialists under one roof and competing for contracts against outsourcing providers in other countries known for similar services.

Challenges remain for the sector to reach its full potential. Reliable and affordable high speed internet is not yet universal, payment systems for receiving international income can be cumbersome, and competition from freelancers in other countries is intense. Building trust with overseas clients, maintaining consistent quality, and navigating time zone differences all require real skill and persistence.

Even so, the freelancing and outsourcing economy represents a meaningful diversification of Bangladesh's income sources beyond traditional industries like garments and agriculture. As digital infrastructure continues to improve and more young people gain access to relevant training, this sector is likely to keep growing, offering an increasingly important path to economic opportunity for a new generation. As more young people gain confidence navigating international clients and platforms, the skills built through freelancing often translate into broader career opportunities within the wider digital economy as well.`,
  },
  {
    title: "Agriculture and Food Security",
    text: `Agriculture has long been the backbone of the Bangladeshi economy, and although its share of national output has declined as industry and services have grown, it remains central to the livelihoods of a large portion of the population and to the country's overall food security. The fertile alluvial soil deposited by its river systems, combined with a climate well suited to rice cultivation, has allowed Bangladesh to become one of the world's major rice producing nations despite having a relatively small land area for its population.

Rice is by far the dominant crop, grown in multiple seasons throughout the year thanks to the availability of water and favorable temperatures. Farmers typically cultivate several varieties suited to different conditions, from flood tolerant strains grown in low lying areas to shorter duration varieties that fit into tighter planting schedules. Beyond rice, the country also produces significant quantities of vegetables, fruits, jute, tea, and fish, the latter coming both from its extensive river and pond systems and from aquaculture operations that have expanded considerably in recent years.

Achieving self sufficiency in staple food production has been a long standing national priority, and the country has made substantial progress on this front. Investments in irrigation, improved seed varieties, and extension services that bring agricultural knowledge directly to farmers have all contributed to steadily rising yields over the decades. Government policies supporting fertilizer subsidies and fair pricing for farmers have also played a role in encouraging continued investment in the sector.

Challenges nonetheless persist. Landholdings in Bangladesh tend to be small and fragmented, limiting the efficiency gains that come with larger scale mechanized farming. Climate related risks, including flooding, cyclones, and salinity intrusion in coastal areas, threaten crop yields and can wipe out a season's harvest for vulnerable farmers. Rising input costs and fluctuating market prices add further uncertainty to farming as a livelihood, prompting many younger people from farming families to seek work in cities or abroad rather than continue in agriculture.

Looking forward, researchers and policymakers are focused on building a more resilient and diversified agricultural sector. This includes developing crop varieties that can withstand flooding, drought, or saline soil, expanding access to crop insurance and credit for smallholder farmers, and encouraging diversification into higher value crops and aquaculture products that can improve farmer incomes beyond what rice alone can provide. Food security remains a foundational concern for a densely populated country, and the continued modernization of its agricultural sector will remain essential to feeding its people and sustaining rural livelihoods for generations to come. Continued collaboration between farmers, researchers, and policymakers will be essential to ensuring that agricultural progress keeps pace with the growing demands of a large and still expanding population in the decades ahead.`,
  },
  {
    title: "The Startup and Tech Scene",
    text: `In recent years, Bangladesh has seen the steady emergence of a homegrown startup ecosystem, as young entrepreneurs build companies aimed at solving everyday problems for a rapidly digitizing population. E commerce platforms, ride sharing services, digital payment providers, and logistics companies are among the ventures that have gained traction, often adapting ideas proven successful elsewhere to the specific needs and constraints of the local market.

Several factors have converged to make this growth possible. A young population, a majority of whom were born after the country's economy began its modern transformation, has grown up with increasing exposure to smartphones and mobile internet. Mobile financial services have made it possible for people without traditional bank accounts to send money, pay bills, and now increasingly shop online, creating fertile ground for digital businesses that would have struggled to reach customers a decade earlier. A growing middle class with rising disposable income has also expanded the pool of potential customers for new digital products and services.

Access to capital, historically one of the biggest obstacles for entrepreneurs in developing economies, has gradually improved. Local angel investors, venture capital funds, and international investors interested in emerging markets have begun putting money into promising Bangladeshi startups, though funding levels still lag behind more mature startup hubs elsewhere in the region. Startup incubators and accelerator programs, often affiliated with universities or supported by development organizations, have also sprung up to help early stage founders refine their business models and pitch to investors.

The challenges facing the ecosystem are significant. Regulatory processes for registering and running a business can be slow and complex, infrastructure gaps such as inconsistent internet speeds outside major cities limit market reach, and competition for skilled technical talent, particularly experienced software engineers, is intense as more companies compete for a limited pool. Founders often need to be resourceful, building lean teams and finding creative ways to reach customers without the marketing budgets available to companies in wealthier markets.

Success stories in areas like digital payments and e commerce have demonstrated that Bangladeshi startups can build genuinely large scale businesses serving millions of users. These early successes have, in turn, inspired a new generation of founders and encouraged more graduates to consider entrepreneurship rather than only traditional corporate or government careers. As internet infrastructure continues to expand into smaller towns and rural areas, the potential customer base for digital businesses will only grow, suggesting that the country's startup scene, while still young compared to more established hubs, has considerable room to mature and expand in the years ahead. Continued investment in digital infrastructure, entrepreneurship education, and a more supportive regulatory environment will likely determine how quickly the ecosystem can close the gap with more established regional startup hubs.`,
  },
  {
    title: "Education System and Literacy Progress",
    text: `Bangladesh has made significant strides in expanding access to education and improving literacy rates since gaining independence, transforming a system that once reached only a small fraction of children into one that now provides at least primary schooling to the vast majority of the population. This progress reflects decades of sustained investment by the government, alongside considerable contributions from non governmental organizations that have run schools and literacy programs in areas the formal system struggled to reach.

Primary education enrollment rates have risen dramatically, and the gender gap that once saw far fewer girls attending school than boys has narrowed substantially, with girls now enrolling in numbers roughly equal to or in some measures exceeding boys at the primary and secondary levels. Programs that provide stipends to families for keeping girls in school, along with broader social changes around the value of educating daughters, have contributed to this shift. Literacy rates among young adults have climbed steadily as a result, even though the country still faces work to do in reaching universal adult literacy across all generations.

The structure of the education system includes primary school, followed by secondary and higher secondary levels, with students eventually able to pursue university education at public or private institutions, or specialize through vocational and technical training programs. Madrasa education, a religious schooling track that also incorporates general subjects, serves a significant portion of students, particularly in rural areas, alongside the mainstream general education system.

Despite the gains, challenges remain substantial. Quality of education varies considerably between well resourced urban schools and under resourced rural ones, with issues like overcrowded classrooms, teacher shortages, and inconsistent training affecting learning outcomes in many areas. Dropout rates, particularly at the transition from primary to secondary school, remain a concern, often driven by economic pressures that push children, especially from poorer families, toward work instead of continued schooling. Early marriage also continues to interrupt the education of some girls despite legal protections and awareness campaigns aimed at reducing the practice.

Looking ahead, policymakers have increasingly focused on improving the quality rather than simply the quantity of education, recognizing that access alone does not guarantee that students are learning effectively. Investments in teacher training, updated curricula that emphasize practical and critical thinking skills, and the gradual introduction of digital learning tools in classrooms are all part of this ongoing effort. As the country's economy continues to shift toward more skilled and technology driven industries, ensuring that its education system can produce graduates equipped for these opportunities will remain one of the most important long term investments the nation can make in its own future. Sustained collaboration among government agencies, teachers, families, and international partners will remain essential to translating these ambitions into consistent classroom results nationwide.`,
  },
  {
    title: "Cultural Festivals and Traditions",
    text: `Bangladesh's cultural calendar is rich with festivals that reflect the country's blend of religious traditions, agricultural rhythms, and a strong sense of linguistic and national identity. These celebrations bring communities together across the year, offering visitors and residents alike a window into the values and history that shape everyday life in the country.

Among the most widely celebrated occasions is Pohela Boishakh, the Bengali New Year, which falls in mid April and is marked by colorful processions, traditional music, and festive markets selling sweets, crafts, and seasonal foods. The celebration is notable for its inclusive, cultural rather than strictly religious character, drawing participation from people of many different faiths and backgrounds who come together to welcome the new year with shared enthusiasm. Streets fill with decorated floats and performers, and families often gather to eat traditional dishes associated with the holiday.

Religious festivals also play a central role in the cultural calendar. Eid celebrations, marking the end of the fasting month and commemorating other significant occasions in the Islamic calendar, are observed with prayers, family gatherings, and the exchange of gifts and new clothing. Durga Puja, one of the most significant festivals for the Hindu community, is celebrated with elaborate temporary shrines, cultural performances, and processions, reflecting the country's religious diversity even though the majority of the population practices Islam.

Language holds a particularly powerful place in the national identity, commemorated each year on International Mother Language Day, which traces its origins to a movement in the country's history when students and activists demonstrated in defense of their linguistic heritage. The day is observed with solemn ceremonies, the laying of wreaths at memorial monuments, and cultural programs that honor the sacrifices made in that earlier struggle, a legacy that continues to shape how the country understands its own identity.

Beyond the major national and religious observances, countless local and seasonal festivals mark the agricultural calendar and regional traditions, from harvest celebrations tied to the rice growing seasons to boat races held on rivers during particular times of year. Folk music, traditional dance forms, and storytelling traditions passed down through generations remain very much alive at these gatherings, even as modern entertainment and digital media have introduced new cultural influences, particularly among younger generations in urban areas.

Together, these festivals illustrate a society that holds onto its traditions while remaining open to change, weaving together religious observance, historical memory, and communal celebration into a cultural life that feels both deeply rooted and continuously evolving. For a country with such a diverse population, these shared moments of celebration serve as important threads binding communities together across lines of religion, region, and generation. Preserving these traditions while welcoming new influences remains an ongoing and living part of the nation's cultural story.`,
  },
  {
    title: "The Digital Economy Push",
    text: `Bangladesh has, in recent years, placed significant emphasis on building a digital economy, pursuing a broad set of policies and investments aimed at expanding internet access, promoting electronic government services, and encouraging technology driven business growth across the country. This push reflects a recognition among policymakers that future economic competitiveness will depend heavily on digital infrastructure and skills, alongside the traditional industries that have driven growth in past decades.

A central pillar of this effort has been the expansion of internet connectivity, both through mobile networks that now reach the vast majority of the population and through fiber optic infrastructure extending into smaller towns and rural areas that previously had limited or no reliable access. This expanded connectivity has enabled a wide range of digital services, from mobile banking and e commerce to online education platforms that gained particular importance during periods when in person schooling was disrupted.

Digitizing government services has been another major focus, with efforts to move processes like paying utility bills, applying for official documents, and accessing certain public services online rather than requiring citizens to visit government offices in person. These changes aim to reduce bureaucratic delays and opportunities for informal payments that have historically frustrated citizens dealing with government processes, while also making services more accessible to people living far from administrative centers.

The push toward a digital economy has also included efforts to build a domestic technology workforce capable of supporting this growth. Training programs targeting young people in areas like software development, digital marketing, and data analysis have expanded, often in partnership with private companies seeking skilled workers and international organizations interested in supporting the country's economic development. Special economic zones dedicated to technology companies and software exports have been established to attract both domestic and foreign investment into the sector.

Financial technology has proven to be one of the more visible successes within this broader digital push. Mobile money services have brought basic financial services to a very large number of people who previously operated entirely outside the formal banking system, enabling everything from remittance transfers to small business payments to happen through a mobile phone rather than requiring a trip to a physical bank branch.

Challenges remain in fully realizing the vision of a comprehensive digital economy, including gaps in digital literacy, uneven internet quality between urban and rural areas, and cybersecurity concerns that grow as more services and money move online. Even so, the sustained commitment to digital transformation represents a significant shift in how the country is positioning itself economically, aiming to leverage technology as a tool for both economic growth and more efficient, accessible public services for its citizens. Sustained investment and coordinated policy will determine how quickly these ambitions become an everyday reality for citizens nationwide.`,
  },
  {
    title: "Youth Entrepreneurship",
    text: `With one of the youngest populations in the world, Bangladesh has increasingly looked to youth entrepreneurship as both an economic opportunity and a practical response to the challenge of creating enough jobs for the large number of young people entering the workforce each year. Traditional employment paths, whether in government service or established private companies, cannot absorb every graduate, prompting a growing number of young people to consider starting their own ventures instead.

This shift has been supported by a changing cultural attitude toward entrepreneurship. Where earlier generations often viewed stable salaried employment, particularly in government or established corporations, as the most respectable and secure career path, a growing number of young Bangladeshis now see starting a business as a legitimate and even preferred option, particularly as success stories from the local startup scene have become more visible and widely discussed.

Access to resources that support young entrepreneurs has expanded in parallel. Universities have begun offering entrepreneurship courses and running business plan competitions, while incubators and co working spaces have opened in major cities, providing not just physical workspace but also mentorship, networking opportunities, and sometimes direct access to early stage funding. Government agencies and non governmental organizations have also introduced programs specifically aimed at supporting young business owners, including microloans, skills training, and simplified business registration processes designed to lower the barriers to getting started.

The types of businesses young entrepreneurs are building span a wide range, from small scale local ventures such as food delivery services and handicraft businesses that sell through social media, to more ambitious technology startups aiming to scale nationally or even regionally. Social media platforms have proven particularly important for young entrepreneurs, allowing them to market products and reach customers without needing the capital required to open a physical storefront, effectively lowering the cost of starting a small business to a level that was not previously possible.

Significant obstacles remain, however. Access to affordable credit is still limited for many young entrepreneurs who lack collateral or an established credit history, and navigating regulatory and licensing requirements can be time consuming and confusing for first time business owners. Cultural and family pressure to pursue more conventional, secure careers can also weigh on young people considering entrepreneurship, particularly in more conservative or rural communities where the concept remains less familiar.

Despite these challenges, the growing energy around youth entrepreneurship represents an important shift in how the country's young population is approaching economic opportunity. As more support systems mature and more visible success stories accumulate, this entrepreneurial spirit has the potential to become an increasingly significant driver of innovation and job creation in the years ahead, complementing rather than replacing the traditional industries that have long anchored the national economy.`,
  },
];

export const bangladeshPassages: ExamPassage[] = ARTICLES.map((a, i) => ({
  id: `en-bangladesh-${String(i + 1).padStart(3, "0")}`,
  language: "en" as const,
  category: "Bangladesh",
  title: a.title,
  wordCount: wc(a.text),
  text: a.text,
}));
