// Category: Technology
// ~10 passages, ~500 words each, English. Fill in via content-writing pass.
import type { ExamPassage } from "./types";

function wc(text: string): number {
  return text.trim().split(/\s+/).length;
}

const ARTICLES: { title: string; text: string }[] = [
  {
    title: "Cloud Computing Explained",
    text: `Cloud computing has fundamentally changed how individuals and businesses access computing resources, shifting away from a model where organizations needed to buy, house, and maintain their own physical servers toward one where computing power, storage, and software can be rented on demand from providers who operate massive data centers on their customers' behalf. Understanding the basic concept behind this shift helps explain why cloud computing has become such a foundational part of modern technology infrastructure.

At its core, cloud computing means accessing computing resources over the internet rather than from a physical machine sitting in your own office or home. Instead of a company purchasing servers that sit idle much of the time and require dedicated staff to maintain, update, and secure, that company can rent exactly the computing capacity it needs from a cloud provider, scaling that capacity up during periods of high demand and back down when demand falls, paying only for what is actually used. This flexibility represents one of the most significant advantages of the cloud model compared to traditional, self managed infrastructure.

Cloud services are generally organized into a few broad categories. Infrastructure services provide basic computing building blocks like virtual servers and storage, giving customers significant control over how they configure and manage their systems. Platform services provide a more complete environment for building and running applications without needing to manage the underlying servers directly. Software services deliver complete, ready to use applications over the internet, allowing users to simply log in and use a program without installing or maintaining anything themselves. Most people interact with this last category most directly, often without realizing that the email service or document editor they use daily is itself a cloud based application running on infrastructure they never see.

The benefits driving widespread cloud adoption extend beyond simple cost savings. Cloud providers typically offer far greater reliability than most individual organizations could achieve on their own, operating data centers with redundant power, networking, and backup systems designed to keep services running even if individual components fail. They also allow smaller companies to access computing capabilities, such as advanced data processing or global content delivery, that would previously have required massive upfront investment only large corporations could afford.

Despite these advantages, moving to the cloud introduces its own considerations. Organizations must think carefully about data security and privacy when storing sensitive information with an outside provider, and dependence on a single provider's infrastructure means that outages, while relatively rare, can have widespread effects when they occur. Many organizations now use a combination of cloud services from multiple providers alongside some of their own infrastructure, a strategy intended to balance the benefits of cloud computing against the risks of relying too heavily on any single system. As internet connectivity continues to improve globally, cloud computing is likely to remain a central pillar of how technology is built and delivered for the foreseeable future.`,
  },
  {
    title: "Cybersecurity Basics",
    text: `As more of daily life, from banking to communication to healthcare records, moves online, cybersecurity has become an essential concern for individuals, businesses, and governments alike. At its core, cybersecurity refers to the practices and technologies used to protect computer systems, networks, and data from unauthorized access, damage, or theft, and understanding a few basic concepts can help anyone better protect their own digital life.

One of the most common threats individuals face involves phishing, a technique in which attackers send messages, often disguised as legitimate communication from a trusted source, designed to trick recipients into revealing sensitive information like passwords or financial details, or into clicking a link that installs malicious software on their device. These attacks have grown increasingly sophisticated over time, sometimes closely mimicking the appearance and tone of genuine communications, which makes a healthy degree of skepticism toward unexpected messages an important habit for anyone navigating the modern internet.

Passwords remain a foundational, if imperfect, line of defense for most online accounts. Using unique, complex passwords for different accounts significantly reduces risk, since a breach at one service does not then expose a person's other accounts if they reused the same password everywhere. Password managers, tools designed to generate and securely store complex passwords, have become an increasingly recommended solution to the practical challenge of remembering many unique passwords. Multi factor authentication, which requires a second form of verification beyond just a password, such as a code sent to a phone, adds an important additional layer of protection, making it significantly harder for an attacker to access an account even if they manage to obtain the password itself.

For organizations, cybersecurity involves considerably more complex considerations, including protecting networks from unauthorized intrusion, ensuring software is regularly updated to patch known vulnerabilities, training employees to recognize social engineering attempts, and maintaining backup systems that allow operations to recover quickly if data is lost or compromised. Many organizations now employ dedicated security teams and specialized tools designed to monitor networks continuously for suspicious activity, since successfully defending against modern cyber threats generally requires ongoing vigilance rather than a one time setup.

The consequences of inadequate cybersecurity can be severe, ranging from financial loss and identity theft for individuals to significant operational and reputational damage for organizations that experience a serious breach. As attackers continue developing new techniques, cybersecurity remains very much an ongoing effort rather than a problem that gets permanently solved. Staying informed about common threats, maintaining good basic digital hygiene like strong unique passwords and cautious handling of unexpected messages, and keeping software updated are practical steps within reach of nearly everyone, forming a reasonable foundation for personal digital security in an increasingly connected world. Small, consistent habits, practiced routinely, often matter more in the long run than any single advanced security tool.`,
  },
  {
    title: "Mobile App Development",
    text: `The process of building a mobile application involves considerably more than simply writing code that runs on a phone. From initial concept through design, development, testing, and ongoing maintenance after release, creating a successful mobile app requires coordinating many different disciplines and making a series of important decisions that shape both how the app is built and how well it ultimately serves its users.

The process typically begins with defining what problem the app is meant to solve and for whom. Clear understanding of the target audience and their needs shapes nearly every subsequent decision, from which features to prioritize to how the interface should be designed. Developers must also decide early on which platforms to target, since apps built for one major mobile operating system are not automatically compatible with others, a decision that has significant implications for both development approach and cost.

Design plays a particularly important role in mobile app development, given the constraints of a small screen and the expectation among users that apps should be simple, intuitive, and fast to navigate. Designers typically create detailed mockups and interactive prototypes before any code is written, allowing the team to test and refine the user experience early, when changes are still relatively inexpensive to make, rather than after significant development work has already been completed based on a flawed design.

On the technical side, developers choose between building an app natively for a specific platform, using tools and programming languages designed specifically for that operating system, or using cross platform frameworks that allow a single codebase to run on multiple platforms with some shared code. Native development often produces apps with the best possible performance and access to the full range of device features, while cross platform approaches can reduce development time and cost, particularly for teams that need to support multiple platforms with limited resources.

Testing represents another essential phase, since mobile apps must function correctly across an enormous variety of device models, screen sizes, and operating system versions, a level of variation considerably greater than what developers typically face with other kinds of software. Thorough testing helps catch bugs, performance issues, and usability problems before an app reaches users, since negative early reviews following a rocky release can be difficult for an app to recover from.

Even after an app launches, the work is far from finished. Developers must continue releasing updates to fix bugs, address security vulnerabilities, maintain compatibility with new operating system versions, and add new features based on user feedback and changing market expectations. This ongoing maintenance cycle, often extending for years after an app's initial release, represents a significant and sometimes underappreciated part of the overall effort required to build and sustain a successful mobile application over time.`,
  },
  {
    title: "A History of the Internet",
    text: `The internet, now such a fundamental part of daily life that it can be difficult to imagine the world without it, has origins that trace back to research projects exploring how to connect separate computer networks together in a reliable and resilient way. Understanding this history offers useful context for appreciating both how far the technology has come and why it works the way it does today.

Early networking research in the mid twentieth century focused on developing ways for computers at different institutions, often universities and research organizations, to communicate with one another, sharing resources and information across distances that would otherwise have required physically transporting data. These early networks used experimental technology to send data in small packets that could be routed flexibly across a network, an approach that proved more resilient than earlier methods and laid important technical groundwork for what would eventually become the modern internet.

Over subsequent decades, the technical standards that allow different networks to communicate with one another regardless of what specific hardware or software they used were developed and refined, allowing what had been a collection of separate, incompatible networks to gradually merge into a single interconnected system. This standardization was a crucial step, since it meant a computer built by one manufacturer, running one kind of network, could exchange information seamlessly with a completely different system elsewhere in the world, a foundational principle that continues to underpin how the internet functions today.

The internet remained primarily a tool for researchers, universities, and government institutions for a considerable stretch of its early history, largely unknown to the general public. This changed significantly with the development of the World Wide Web, a system built on top of the existing internet infrastructure that introduced the concept of linked pages accessible through a relatively simple interface, making the internet dramatically more approachable for ordinary users without specialized technical knowledge. The introduction of graphical web browsers in the following years further accelerated public adoption, opening the internet to a mainstream audience for the first time.

The following decades saw explosive growth in internet usage, accompanied by the rise of search engines that helped users navigate the rapidly expanding volume of available content, e commerce platforms that transformed how people shop, and eventually social media platforms that changed how people communicate and share information with one another. The shift toward mobile internet access, enabled by increasingly capable smartphones and expanding wireless networks, represented another major turning point, making constant internet connectivity a normal part of daily life for billions of people around the world.

Today's internet, supporting everything from video streaming to cloud computing to the vast infrastructure of modern commerce and communication, bears the clear mark of decisions made by researchers decades ago, even as the scale and application of the technology have grown far beyond what those early developers likely imagined when they first began experimenting with ways to connect a handful of computers together.`,
  },
  {
    title: "Renewable Energy Technology",
    text: `Renewable energy technology has advanced considerably over recent decades, transforming what was once a relatively niche and expensive alternative to fossil fuels into an increasingly mainstream and cost competitive component of the global energy mix. Understanding the main types of renewable technology and the challenges they still face helps clarify both the genuine progress made and the work that remains as countries work to shift their energy systems.

Solar power, generated by converting sunlight directly into electricity using specialized panels, has seen some of the most dramatic technological and cost improvements of any energy source in recent history. Manufacturing improvements and economies of scale have driven down the cost of solar panels substantially compared to earlier decades, making solar installations increasingly practical for everything from individual homes to massive utility scale power plants covering large areas of land. Advances in panel efficiency continue to allow more electricity to be generated from the same physical footprint, further improving the economics of solar power over time.

Wind power, generated by turbines that convert the kinetic energy of moving air into electricity, has similarly matured into a major source of renewable electricity in many parts of the world. Modern wind turbines are considerably larger and more efficient than earlier generations, and offshore wind installations, built in bodies of water where wind tends to blow more consistently than on land, have opened up significant additional capacity in coastal regions, though they generally involve higher construction and maintenance costs than land based installations.

A persistent technical challenge facing both solar and wind power involves their inherently variable nature, since solar panels only generate electricity when the sun is shining and wind turbines only generate power when wind conditions are favorable. This variability has driven significant investment and research into energy storage technology, particularly large scale batteries capable of storing excess electricity generated during periods of high production for use later when generation drops, helping smooth out the mismatch between when renewable energy is generated and when it is actually needed by consumers.

Beyond solar and wind, other renewable technologies continue to play important roles in specific contexts, including hydroelectric power generated from flowing water, geothermal energy that taps heat from within the earth, and various forms of bioenergy derived from organic material. Each of these technologies has its own particular advantages and geographic or environmental constraints that determine where it makes the most practical sense to deploy.

As renewable technology continues to improve and costs continue to decline, an increasing number of countries and utility companies have incorporated significant amounts of renewable generation into their overall energy systems. Continued advances in energy storage, more efficient generation technology, and modernized electrical grids capable of managing a more variable mix of energy sources will likely remain central themes as the broader transition toward cleaner energy systems continues to unfold in the years ahead.`,
  },
  {
    title: "Wearable Devices",
    text: `Wearable technology, referring to electronic devices designed to be worn on the body, has evolved considerably from simple novelty gadgets into a category of products that many people now use daily to monitor their health, stay connected, and track various aspects of their physical activity. Smartwatches and fitness trackers represent the most widely adopted examples, though the broader category also includes items like smart glasses, connected clothing, and specialized medical monitoring devices.

At the heart of most consumer wearables lies a combination of small sensors capable of measuring physical signals such as heart rate, movement, and in some more advanced devices, blood oxygen levels or skin temperature. These sensors, combined with software that processes and interprets the raw data they collect, allow wearable devices to provide users with ongoing insight into aspects of their health and activity that would previously have required specialized medical equipment or manual tracking to observe.

Fitness tracking represents one of the most popular applications of wearable technology, with devices counting steps, estimating calories burned, monitoring sleep patterns, and tracking specific types of exercise, giving users continuous feedback intended to encourage healthier habits. Many people find that having this kind of data readily available, often displayed alongside longer term trends and goals within a companion smartphone application, provides meaningful motivation to stay active that they might not maintain without the device's regular feedback and reminders.

Beyond fitness, wearable devices have increasingly taken on communication functions as well, allowing users to receive notifications, respond to messages, and in some cases make phone calls directly from their wrist without needing to take out their phone. This convenience factor has been a significant driver of adoption, particularly among users who want to stay connected during activities where checking a phone would be impractical or unwelcome, such as during exercise or in professional settings.

Healthcare applications of wearable technology represent a particularly promising and rapidly developing area. Some devices now offer features capable of detecting irregular heart rhythms or monitoring specific health conditions on an ongoing basis, providing both users and, in some cases, their healthcare providers with continuous data that would previously have required periodic clinical visits to capture. This kind of continuous monitoring has the potential to catch developing health issues earlier than they might otherwise be noticed, though these consumer focused features are generally intended to complement rather than replace regular medical care and professional diagnosis.

As sensor technology continues to improve and battery life extends, wearable devices are likely to take on an increasingly capable and central role in how people monitor their own health and stay connected throughout the day. Privacy considerations around the large amounts of personal health data these devices collect remain an important and ongoing area of discussion, as manufacturers, regulators, and users continue working out appropriate standards for how this sensitive information should be collected, stored, and protected.`,
  },
  {
    title: "Understanding 5G Networks",
    text: `5G refers to the fifth generation of mobile network technology, representing a significant upgrade over previous generations in terms of speed, capacity, and the ability to support a much larger number of connected devices simultaneously. While most people encounter 5G primarily through faster internet speeds on their smartphones, the technology's full significance extends considerably beyond simply making video streaming or file downloads quicker.

One of the most noticeable improvements 5G brings is dramatically increased data speed compared to earlier network generations, allowing users to download large files, stream high resolution video, and use data intensive applications with considerably less delay than previous mobile networks could reliably support. This speed improvement comes partly from the use of additional radio frequency bands, including higher frequency ranges capable of carrying much more data, though these higher frequencies also travel shorter distances and are more easily blocked by physical obstacles, requiring a denser network of transmission equipment to provide consistent coverage.

Beyond raw speed, 5G was also designed with much lower latency in mind, referring to the delay between sending a request and receiving a response over the network. This reduction in latency matters significantly for applications where near instantaneous response time is important, such as certain online games, video calls, and emerging applications like remote control of machinery or vehicles, where even small delays could meaningfully affect performance or safety.

Perhaps the most significant long term implication of 5G technology involves its capacity to support a vastly larger number of connected devices within a given area compared to previous network generations. This capability is particularly relevant to the continued growth of connected devices beyond smartphones, including sensors used in smart city infrastructure, industrial equipment, connected vehicles, and countless other devices that increasingly rely on wireless connectivity to function. Earlier network generations were not designed with this scale of device connectivity in mind, making 5G an important enabling technology for the continued expansion of this broader category of connected devices.

Rolling out 5G networks has required substantial infrastructure investment from telecommunications companies, including the installation of many additional transmission sites to achieve the coverage density the technology often requires, particularly for its highest speed frequency bands. This has meant that 5G availability and performance can vary considerably between different regions, with dense urban areas typically seeing the most complete deployment while rural areas sometimes take longer to receive full coverage.

As 5G infrastructure continues to expand and mature, its impact is expected to extend well beyond faster smartphones, potentially enabling new applications across industries that depend on fast, reliable, and highly responsive wireless connectivity. Understanding 5G as more than simply a faster version of previous mobile networks helps clarify why the technology has received such significant attention and investment from telecommunications companies and technology developers around the world.`,
  },
  {
    title: "Open Source Software",
    text: `Open source software refers to computer programs whose underlying source code is made publicly available, allowing anyone to view, modify, and distribute the software according to specific licensing terms, in contrast to proprietary software where the source code remains private and controlled exclusively by the company or individual that developed it. This model of software development has become an enormously influential force in the technology industry, underlying much of the infrastructure that powers the modern internet.

The core philosophy behind open source software rests on the idea that collaborative, transparent development, where many contributors can review, improve, and build upon existing code, tends to produce more robust and reliable software than development conducted entirely behind closed doors. When source code is publicly available, bugs and security vulnerabilities can potentially be identified and fixed by anyone in the community with the relevant expertise, not just the original development team, and features can be added or improved by contributors who see a particular need the original developers may not have prioritized.

Open source projects vary enormously in scale and organization, ranging from small tools maintained by a single volunteer developer to massive, foundational projects that involve contributions from thousands of developers around the world and receive significant financial support from major technology companies that rely on the software for their own operations. Many of the fundamental building blocks of internet infrastructure, including operating systems, web servers, and programming languages, exist as open source projects that anyone can examine, use, and contribute to.

The business case for companies to invest in and contribute to open source software might seem counterintuitive at first glance, since it involves giving away code that competitors could also use freely. In practice, many companies find substantial benefits in this model, including reduced development costs achieved by building on shared, community maintained tools rather than building everything from scratch, improved software quality resulting from broader community scrutiny, and goodwill or recruiting advantages gained by contributing visibly to widely used projects that many developers respect and rely upon.

Open source licensing comes in several different forms, each specifying different terms for how the software can be used, modified, and redistributed. Some licenses impose relatively few restrictions, while others require that any software built using the open source code must also be released under similarly open terms, a requirement intended to ensure that improvements to the software remain available to the broader community rather than being incorporated into closed, proprietary products without any benefit flowing back to the original project.

Today, open source software forms an essential and often invisible foundation underlying a huge portion of modern technology, from the servers that power major websites to the operating systems running on countless devices. Its continued development, sustained by a combination of volunteer contribution and significant corporate investment, illustrates how collaborative, transparent approaches to building software have proven capable of producing some of the most widely trusted and heavily used technology in the world today.`,
  },
  {
    title: "Data Privacy in the Digital Age",
    text: `As more aspects of daily life move online, from shopping and banking to healthcare and social interaction, the amount of personal data collected, stored, and analyzed by various organizations has grown enormously, making data privacy an increasingly important concern for individuals and a significant area of focus for regulators around the world. Understanding what data privacy actually involves helps clarify why it has become such a widely discussed topic.

Personal data, in this context, refers to any information that can be linked to a specific individual, ranging from obviously sensitive information like financial details and health records to seemingly minor details like browsing history, location data, and online purchase patterns that, when combined and analyzed together, can reveal surprisingly detailed insights about a person's habits, preferences, and daily life. Many online services collect this kind of data as a routine part of their operation, often using it to personalize content, target advertising, or improve their own products based on how people actually use them.

Concerns about data privacy generally center on several related issues. One involves the question of consent, and whether individuals genuinely understand and agree to how their data will be collected and used, given that privacy policies describing these practices are often long, filled with technical or legal language, and rarely read carefully by the people they are meant to inform. Another concern involves data security, since any organization that collects large amounts of personal information becomes a potential target for hackers, and a breach at a major company can expose sensitive information belonging to millions of people at once. A further concern involves how collected data might be used beyond its original purpose, whether shared with third parties, sold to advertisers, or used in ways the original individual never anticipated or explicitly agreed to.

In response to growing public concern, many governments have introduced data protection regulations that establish specific rights for individuals regarding their personal information, such as the right to know what data a company has collected about them, the right to request that data be deleted, and requirements that companies obtain clearer consent before collecting or using certain types of sensitive information. These regulations have prompted many companies to significantly overhaul how they handle personal data, implementing clearer privacy policies and giving users more direct control over their own information.

For individuals, practical steps toward protecting personal privacy include being thoughtful about what information is shared online, reviewing and adjusting privacy settings on frequently used platforms, and paying attention to the permissions requested by apps and services before granting access to things like location data or contact lists. While no set of individual precautions can eliminate privacy risk entirely in an increasingly connected world, combining informed personal habits with the protections established through evolving regulation represents the most practical current approach to managing this ongoing and evolving challenge.`,
  },
  {
    title: "Robotics and Automation",
    text: `Robotics and automation technology has moved well beyond the industrial assembly lines where it first gained widespread use, increasingly touching areas from healthcare to agriculture to everyday household tasks. Understanding the basic distinction between these related but distinct concepts, along with a sense of where the technology is headed, helps clarify both its current impact and its likely future trajectory.

Automation, broadly speaking, refers to using technology to perform tasks with minimal direct human involvement, and does not necessarily require a physical robot at all; software that automatically processes data or manages a workflow without human intervention is also a form of automation. Robotics specifically refers to physical machines designed to sense their environment and perform physical tasks, sometimes autonomously and sometimes under direct human control, ranging from large industrial arms that weld and assemble products to small robots designed to navigate and clean household floors.

Industrial robotics remains one of the most established and economically significant applications of this technology, with robotic arms performing repetitive, precise tasks on manufacturing lines with a level of speed and consistency difficult for human workers to match over long shifts. These systems have become increasingly sophisticated over time, incorporating sensors and, increasingly, artificial intelligence that allows them to adapt to slight variations in their task rather than requiring everything to be positioned with perfect precision, a flexibility that has expanded the range of tasks robots can reliably perform.

Beyond traditional manufacturing, robotics has found significant application in areas like warehouse logistics, where robots navigate large storage facilities to help locate, transport, and sort products as part of increasingly automated fulfillment operations. In agriculture, robotic and automated systems assist with tasks like planting, monitoring crop health, and harvesting certain crops, helping address labor shortages while potentially improving precision compared to some traditional farming methods. In healthcare, robotic systems assist surgeons with certain procedures, offering enhanced precision and control, while other robots handle tasks like transporting supplies within hospital settings, freeing up staff time for more direct patient care.

Consumer robotics has also grown significantly, with robotic vacuum cleaners and similar household devices becoming increasingly common, along with early stage development of more general purpose robots intended to assist with a broader range of household tasks, though these more ambitious general purpose systems remain considerably less mature and widespread than specialized robots designed for a single specific task.

Looking forward, continued advances in sensors, artificial intelligence, and mechanical engineering are expected to expand both the capabilities and the range of practical applications for robotics across nearly every industry. Questions about the impact of increasing automation on employment, along with the technical and safety challenges involved in deploying robots more widely in unpredictable, human occupied environments, remain important considerations shaping how quickly and in what form this continued expansion actually unfolds in the years ahead.`,
  },
];

export const technologyPassages: ExamPassage[] = ARTICLES.map((a, i) => ({
  id: `en-technology-${String(i + 1).padStart(3, "0")}`,
  language: "en" as const,
  category: "Technology",
  title: a.title,
  wordCount: wc(a.text),
  text: a.text,
}));
